<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Name-&amp;-ID" data-toc-modified-id="Name-&amp;-ID-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Name &amp; ID</a></span></li><li><span><a href="#Problem-#-A" data-toc-modified-id="Problem-#-A-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Problem # A</a></span><ul class="toc-item"><li><span><a href="#A-1" data-toc-modified-id="A-1-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>A-1</a></span></li><li><span><a href="#A-2" data-toc-modified-id="A-2-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>A-2</a></span></li><li><span><a href="#A-3" data-toc-modified-id="A-3-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>A-3</a></span></li><li><span><a href="#A-4" data-toc-modified-id="A-4-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>A-4</a></span></li><li><span><a href="#A-5" data-toc-modified-id="A-5-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>A-5</a></span></li><li><span><a href="#A-6" data-toc-modified-id="A-6-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>A-6</a></span></li><li><span><a href="#A-7" data-toc-modified-id="A-7-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>A-7</a></span></li><li><span><a href="#A-8" data-toc-modified-id="A-8-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>A-8</a></span></li><li><span><a href="#A-9" data-toc-modified-id="A-9-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>A-9</a></span></li><li><span><a href="#A-10" data-toc-modified-id="A-10-2.10"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>A-10</a></span></li><li><span><a href="#Rough-Work" data-toc-modified-id="Rough-Work-2.11"><span class="toc-item-num">2.11&nbsp;&nbsp;</span>Rough Work</a></span></li></ul></li></ul></div>

# Name & ID

Group Number:  

        Student Names: 1- Mohammed Al Nasser   
                        2- Abdulmohsen Al Ali
        Student IDs: 1- 202034520
                        2-

# Problem # A

## A-1

In [30]:
# Answers to A-1
# First, start with determining your problem or objectives and a further understanding
# of data will help in facilitating the implemintaion of a classification alogrithm.

# Second, a cleaning and execluding for unwanted data to prepare the data for proccessing.
#  Also, formating might be handful for the data-proccessing.

# Third,comes the training procdure of the model(method). Therefore, spiliting the data
# between train and test is needed.

# Forth, Train the classification model: Once you have the training and test sets,
#  you can train a classification model using the training set. This involves selecting
#  a classification algorithm, training the model on the training data, and fine-tuning the model's hyperparameters to improve its performance.

# Fifth, You can evaluate the model's performance using a variety of metrics after training it using the test set,
# including accuracy, precision, and recall. This will give you a sense of how well the model is able to generalize to unseen data. 


## A-2

In [31]:
# Answers to A-2
##a) Using ID3, you can build a model of decisions and their consequences
#  that looks like a tree. Based on the values of the features, 
# a tree is constructed from the root node and separated into smaller
# and smaller subsets. The tree is built by selecting the feature that
# provides the greatest information gain at each step, and repeating 
# the process until all the data points in the subset have the same class label.
# Naive Bayes, on the other hand, is a probabilistic classifier that makes predictions
# based on the probability of a given class given the data point's features. 
# The ID3 method is generally considered to be more accurate than the Naive Bayes in most cases.

#b) Classification rules are used to predict the class or category of a given data point based on its features,
# while association rules are used to identify relationships between different items in a dataset.
# Classification rules are typically used in supervised learning, where the data is labeled with the correct class,
# while association rules are typically used in unsupervised learning, where the data is not labeled and the goal is to discover hidden patterns and relationships in the data.

## A-3

In [32]:
# Answers to A-3
print("Entropy measures the uncertainty, randomness, or disoreder.")
print("When the entropy is 0, it means that the system is perfectly ordered.")

Entropy measures the uncertainty, randomness, or disoreder.
When the entropy is 0, it means that the system is perfectly ordered.


## A-4

In [33]:
# Answers to A-4
print("""Using methods like decision tree overfits the data, making it difficult to handle new data.
A way to avoid this overfits is to use many decision trees which will remove records randomly.
The resultant of the way is many random decision trees called as random forest.
And this is an example of a general idea called ensemble methods.""")


Using methods like decision tree overfits the data, making it difficult to handle new data.
A way to avoid this overfits is to use many decision trees which will remove records randomly.
The resultant of the way is many random decision trees called as random forest.
And this is an example of a general idea called ensemble methods.


## A-5

In [100]:
# Answers to A-5
import pandas as pd
from sklearn.preprocessing import LabelEncoder


df = pd.read_excel("HW4_DataA.xlsx")
df2 = df.copy()
display(df.head())
display(df.info())
print("There is no inconsistency")
df.drop("StdID", inplace=True, axis=1)
null_columns=df.columns[df.isna().any()]
print('Columns with NaN values are:', null_columns)
print("There are no Nan values in the data frame")

pl_mapping = {'Fair':1,'Good':2, 'Excellent':3}
df['Prog_level'] = df['Prog_level'].map(pl_mapping)

# con_mapping = {'NC':0,'BA':1, 'DS':2, 'DA':3}
# df['Concentration'] = df['Concentration'].map(con_mapping)

df = pd.get_dummies(df, columns=["Job_Offered"],drop_first=True)
df = pd.get_dummies(df, columns=["Gender"],drop_first=True)
df = pd.get_dummies(df, columns=["Field_Exp"],drop_first=True)



encoder = LabelEncoder()
encoder.fit(df["Concentration"])
df["Concentration"]=encoder.transform(df["Concentration"])
conc = list(df["Concentration"])
df.drop("Concentration", inplace=True, axis=1)
df["Concentration"] = conc
display(df.head())

StdID Job_Offered  STAT_Courses Prog_level Gender  MATH_Courses Field_Exp  \
0  s11128          No             3       Fair      M             2       INT   
1  s11285         Yes             1       Good      M             4        ST   
2  s11354          No             1       Good      M             4        ST   
3  s11539          No             3       Fair      M             3       INT   
4  s11726          No             3       Fair      F             2       INT   

   GPA  Num_semesters Concentration  
0  2.7             10            BA  
1  2.9             10            NC  
2  3.2              7            DS  
3  2.9             10            BA  
4  2.9             10            BA

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   StdID          175 non-null    object 
 1   Job_Offered    175 non-null    object 
 2   STAT_Courses   175 non-null    int64  
 3   Prog_level     175 non-null    object 
 4   Gender         175 non-null    object 
 5   MATH_Courses   175 non-null    int64  
 6   Field_Exp      175 non-null    object 
 7   GPA            175 non-null    float64
 8   Num_semesters  175 non-null    int64  
 9   Concentration  175 non-null    object 
dtypes: float64(1), int64(3), object(6)
memory usage: 13.8+ KB


None

There is no inconsistency
Columns with NaN values are: Index([], dtype='object')
There are no Nan values in the data frame


STAT_Courses  Prog_level  MATH_Courses  GPA  Num_semesters  \
0             3           1             2  2.7             10   
1             1           2             4  2.9             10   
2             1           2             4  3.2              7   
3             3           1             3  2.9             10   
4             3           1             2  2.9             10   

   Job_Offered_Yes  Gender_M  Field_Exp_ST  Concentration  
0                0         1             0              0  
1                1         1             1              3  
2                0         1             1              2  
3                0         1             0              0  
4                0         0             0              0

## A-6

In [44]:
# Answers to A-6
import numpy as np
from sklearn.model_selection import train_test_split
X = df.iloc[:,:-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = df.iloc[:120, :-1], df.iloc[120: , :-1], df.iloc[:120, -1], df.iloc[120: , -1]
np.unique(y_test, return_counts=True)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
from sklearn import tree
dtClf = tree.DecisionTreeClassifier(random_state=0,criterion='entropy',splitter='best')
dtClf = dtClf.fit(X_train,y_train)
import matplotlib.pyplot as plt
plt.figure(figsize =(10,10),dpi=1000)
tree.plot_tree(dtClf,feature_names=df.columns[:-1].tolist(),class_names=['0','1','2','3'],filled=True,rounded=True); 
plt.show()

dt_y_pred = dtClf.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix
print("Decision Tree: \n")
print("Accuracy:=",  accuracy_score(y_test, dt_y_pred))
print("Confusion Matrix:= \n", confusion_matrix(y_test, dt_y_pred) )

Decision Tree: 

Accuracy:= 0.8909090909090909
Confusion Matrix:= 
 [[17  0  0  0]
 [ 0  8  5  0]
 [ 0  0  9  0]
 [ 0  0  1 15]]


## A-7

In [45]:
# Answers to A-7
from scipy.stats import entropy
probs=df['Concentration'].value_counts()/len(df.index)
E_Concentration=entropy(probs,base=2)

split = pd.crosstab(df['Concentration'],df['MATH_Courses'])  

Split_Probs=split/split.sum() 

E_Concentration_2 = entropy(Split_Probs[2],base=2)
E_Concentration_3 = entropy(Split_Probs[3],base=2)
E_Concentration_4 = entropy(Split_Probs[4],base=2)
E_Concentration_18 = entropy(Split_Probs[18],base=2)
E_Concentration_19= entropy(Split_Probs[19],base=2)

probs=df['MATH_Courses'].value_counts()/len(df.index) 

E_Concentration_MATH_Courses =np.average([E_Concentration_2,E_Concentration_3, E_Concentration_4, E_Concentration_18, E_Concentration_19],weights=[probs[2],probs[3], probs[4], probs[18], probs[19]])

IG = E_Concentration - E_Concentration_MATH_Courses
print(f'The information gain is {IG:0.4f}.')

The information gain is 0.7683.


## A-8

In [ ]:
# Answers to A-8

## A-9

In [98]:
# Answers to A-9
display(df2.loc[:,['Prog_level','Field_Exp']].sort_values(by='Field_Exp'))
fair_int = len(df2[(df2['Prog_level'] == 'Fair') & (df2['Field_Exp'] == 'INT')])
print("Rows of Fair - INT:", fair_int)
good_int = len(df2[(df2['Prog_level'] == 'Good') & (df2['Field_Exp'] == 'INT')])
print("Rows of Good - INT:", good_int)
exc_st = len(df2[(df2['Prog_level'] == 'Excellent') & (df2['Field_Exp'] == 'ST')])
print("Rows of Excellent - ST:", exc_st)

print("\nTotal rows of Fair:", len(df2[df2['Prog_level'] == 'Fair']))
print("Total rows of Good:", len(df2[df2['Prog_level'] == 'Good']))
print("Total rows of Excellent:", len(df2[df2['Prog_level'] == 'Excellent']))


print("""\n\n-If the Prog_level = Fair, then Field_Exp = INT\nthe above rule has coverage/support of 48, and accuracy/condidence of 80%\n
-If the Prog_level = Good, then Field_Exp = INT\mnthe above rule has coverage/support of 48, and accuracy/condidence of 66.67%\n
-If the Prog_level = Excellent, then Field_Exp = ST\nthe above rule has coverage/support of 48, and accuracy/condidence of 33.33%\n
         
(Prog_level = Fair, Field_Exp = INT) has the highest accuracy""")

Prog_level Field_Exp
0         Fair       INT
98   Excellent       INT
99        Good       INT
100       Good       INT
102       Fair       INT
..         ...       ...
61        Good        ST
62        Good        ST
145  Excellent        ST
133       Fair        ST
142       Good        ST

[175 rows x 2 columns]

Rows of Fair - INT: 48
Rows of Good - INT: 48
Rows of Excellent - ST: 17

Total rows of Fair: 60
Total rows of Good: 64
Total rows of Excellent: 51


-If the Prog_level = Fair, then Field_Exp = INT
the above rule has coverage/support of 48, and accuracy/condidence of 80%

-If the Prog_level = Good, then Field_Exp = INT\mnthe above rule has coverage/support of 48, and accuracy/condidence of 66.67%

-If the Prog_level = Excellent, then Field_Exp = ST
the above rule has coverage/support of 48, and accuracy/condidence of 33.33%

         
(Prog_level = Fair, Field_Exp = INT) has the highest accuracy


## A-10

In [43]:
# Answers to A-10
X = df.iloc[:,:-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = df.iloc[:120, :-1], df.iloc[120: , :-1], df.iloc[:120, -1], df.iloc[120: , -1]

from sklearn.naive_bayes import CategoricalNB 
NBClf = CategoricalNB(alpha=1.0, class_prior=None, fit_prior=True)  
NBClf.fit(X_train,y_train)
NB_y_pred = NBClf.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix
print("NB for Categorical Data: \n")
print("Accuracy:=",  accuracy_score(y_test, NB_y_pred))
print("Confusion Matrix:= \n", confusion_matrix(y_test, NB_y_pred) )

print("""It can be observed from the results that the decision tree classifier has better performance than Naive Bayes on the given data.""")

NB for Categorical Data: 

Accuracy:= 0.7636363636363637
Confusion Matrix:= 
 [[16  0  0  1]
 [ 0  8  5  0]
 [ 0  0  8  1]
 [ 2  1  3 10]]
It can be observed from the results that the decision tree classifier has better performance than Naive Bayes on the given data.


## Rough Work